# Generated by Django 5.2.1 on 2025-05-18 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('Prop', 'Prop'), ('Hooker', 'Hooker'), ('Lock', 'Lock'), ('Flanker', 'Flanker'), ('Number Eight', 'Number Eight'), ('Scrum Half', 'Scrum Half'), ('Fly Half', 'Fly Half'), ('Centre', 'Centre'), ('Wing', 'Wing'), ('Full Back', 'Full Back')], max_length=20)),
                ('current_worth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_of_birth', models.DateField()),
                ('spouse', models.CharField(blank=True, max_length=100, null=True)),
                ('children', models.PositiveIntegerField(default=0)),
                ('dummy_field', models.CharField(default='dummy', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField()),
                ('tries_scored', models.PositiveIntegerField()),
                ('successful_tackles', models.PositiveIntegerField()),
                ('overall_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_stats', to='Elite.player')),
            ],
        ),
        migrations.CreateModel(
            name='Scout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
