# Generated by Django 5.2.1 on 2025-06-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0001_alter_team_league_alter_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('category', models.CharField(default='rugby', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='team_logo/main-logo.svg', null=True, upload_to='team_logo'),
        ),
    ]
