# Generated by Django 5.2.1 on 2025-05-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='children',
        ),
        migrations.RemoveField(
            model_name='player',
            name='dummy_field',
        ),
        migrations.RemoveField(
            model_name='player',
            name='spouse',
        ),
    ]
