# Generated by Django 5.2.1 on 2025-05-23 22:33

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0002_remove_player_children_remove_player_dummy_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scout',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='enter a valid phone number', regex='^\\+?1?\\d{10,15}$')]),
        ),
        migrations.AddField(
            model_name='scout',
            name='role',
            field=models.CharField(choices=[('head scout', 'Head Scout'), ('assistant', 'Assistant')], default='memeber', max_length=100),
            preserve_default=False,
        ),
    ]
