# Generated by Django 5.2.1 on 2025-06-05 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0002_news_alter_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='Elite.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='Elite.team')),
            ],
        ),
    ]
