# Generated by Django 5.2.2 on 2025-06-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0003_upcomingmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='/media/team_logo/main_logo.svg', null=True, upload_to='team_logo'),
        ),
    ]
