# Generated by Django 5.2.2 on 2025-06-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0004_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='team_logo/main_logo.svg', null=True, upload_to='team_logo'),
        ),
    ]
