# Generated by Django 5.2.2 on 2025-06-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0005_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancestat',
            name='matches_played',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
