# Generated by Django 5.2.1 on 2025-06-02 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0005_league_scout_teams_team_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(blank=True, choices=[('Super Rugby', 'Super Rugby'), ('Top 14', 'Top 14'), ('Premiership Rugby', 'Premiership Rugby'), ('United Rugby Championship', 'United Rugby Championship'), ('Major League Rugby', 'Major League Rugby')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='Elite.league'),
        ),
    ]
