# Generated by Django 5.2.2 on 2025-06-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0006_alter_performancestat_matches_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancestat',
            name='successful_tackles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancestat',
            name='tries_scored',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
