# Generated by Django 5.2.2 on 2025-06-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0007_alter_performancestat_successful_tackles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancestat',
            name='overall_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
