# Generated by Django 5.2.2 on 2025-06-10 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0008_alter_performancestat_overall_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_matches_as_team1', to='Elite.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_matches_as_team2', to='Elite.team')),
            ],
        ),
    ]
